### PR TITLE
JavaScript can't find initMap() function

### PR DESCRIPTION
**Pull request by HarmHoog**
The map wasn't loading because the initMap() function could not be found. Removing the curly brackets seem to resolve this problem.

### CODE REVIEW

**Comment by dlemmermann** [comment]
Thank you for providing this fix. I think Rob no longer supports this project or create new releases for it. I ended up copying the entire code into our project and removing those brackets. I also converted it into an actual module by adding the module-info.java. Took me only a few minutes. I wished @rterp would return ... me sad.

**Comment by CuteDivinity** [comment]
It would be great if someone would create a fork with all the pull requests and continue this project by this way...

**Comment by dlemmermann** [comment]
Yes, do it! :-)

**Comment by CuteDivinity** [comment]
I am actually beginner and using this for a school project :D, but I will give it a try if no one wants to :-)

**Pull request merged**
